### ISSUE TITLE
resource attribution?

### ISSUE THREAD

**Issue by itdaniher** [zxqfl/TabNine#1]
Might be useful/appropriate to give a shoutout to https://github.com/github/linguist etc.

**Comment by zxqfl** [comment]
Will do.

HN is rate limiting me so I can't respond there, but:

1. Thanks for the note about copyright, I'll add that tonight.
2. License keys are validated once. After that, they work offline.
3. There's no stream cipher. It's just a GET from update.tabnine.com/version, followed by a download if there's a new version. (Keys are validated at tabnine.com and only when entered by the user.)
