### ISSUE TITLE
Deactivation after editor restart

### ISSUE THREAD

**Issue by PhilipTrauner** [zxqfl/TabNine#10]
First of all: TabNine is awesome, immediately purchased it after using it for 5 minutes.
I have one small problem though: Every time I restart Sublime (3180) I have to enter my license again because TabNine seemingly forgets that it is already activated.

Sublime Console output:
```
reloading plugin TabNine.TabNine
reloading settings Packages/TabNine/TabNine.sublime-settings
TabNine: starting version 0.4.7
Exception while interacting with TabNine subprocess: [Errno 32] Broken pipe
TabNine: starting version 0.11.2
```
Displayed warning:  

![image](https://user-images.githubusercontent.com/9287847/48402090-08ad8680-e72b-11e8-9ad5-9c098c2efec7.png)

With kind regards,
Philip Trauner

**Comment by zxqfl** [comment]
Sorry about that, this is definitely a bug. Does the displayed console output appear each time you restart Sublime? That indicates that the TabNine package directory is getting overwritten. This would also explain why you needed to reenter the key, since the key is stored in the package directory.

**Comment by PhilipTrauner** [comment]
Weirdly enough, I can not reproduce the bug anymore as of today 😅 
```
reloading plugin TabNine.TabNine
plugins loaded
TabNine: starting version 0.11.2
```

I'm guessing the issue will crop up again when you decide to release the next update (my interpretation of the first [Sublime Text console output](https://github.com/zxqfl/TabNine/issues/10#issue-380122841))

With kind regards,
Philip Trauner

**Comment by zxqfl** [comment]
Looks like this is because Package Control deletes all existing files in the directory when it does an update. I'll have to push a TabNine updates which moves TabNine config and registration keys to the home directory before updating the Sublime client again.
