### ISSUE TITLE
Feature: Support JavaScript. 

### ISSUE THREAD

**Issue by FreddyJD** [zxqfl/TabNine#104]
I would love to use it at work. JavaScript / Node ?

**Comment by zxqfl** [comment]
We do support JavaScript! The full list (for Deep TabNine) is Python, JavaScript, Java, C++, C, PHP, Go, C#, Ruby, Objective-C, Rust, Swift, TypeScript, Haskell, OCaml, Scala, Kotlin, Perl, SQL, HTML, CSS, and Bash.
