### ISSUE TITLE
the ranking of completion result

### ISSUE THREAD

**Issue by carter54** [zxqfl/TabNine#108]
Hello, very nice work. 
I have a question about the completion ranking when reading TabNine website. Following figs show that the result with the highest probability is not always presented at the top 1 position.  
![image](https://user-images.githubusercontent.com/26741594/62020206-99ae8a00-b1f4-11e9-9b3d-f960cbab4f33.png)
![image](https://user-images.githubusercontent.com/26741594/62020231-bcd93980-b1f4-11e9-937d-889b8eca5eb1.png)
is there a strategy behind the tabnine to decide the trade-off between probability and completion length?
thanks a lot.

**Comment by roangel** [comment]
Was going to report this as well:
![image](https://user-images.githubusercontent.com/21340299/63755862-aee00c80-c8b7-11e9-81ec-cfd3efbf5524.png)

Would be nice to instead of having it alphabetically, having it by probability.
