### ISSUE TITLE
Tabnine semantic completion server installation fail

### ISSUE THREAD

**Issue by liflovs** [zxqfl/TabNine#109]
![image](https://user-images.githubusercontent.com/27358804/62047311-d6897980-b212-11e9-8fb5-2334395927c7.png)

Command works fine in console but this is keep showing up. How troubleshoot the issue?

**Comment by Lunchb0ne** [comment]
I'm using WSL Remote in VS-code and I have the same problem

**Comment by Connum** [comment]
Same problem with VS Code under Windows. Also installed it globally manually, but the message still shows up.

**Comment by liflovs** [comment]
@Lunchb0ne , @Connum manual installation and setting config as in this guide worked https://tabnine.com/semantic

**Comment by Connum** [comment]
For anyone stumbling upon this: Under Windows, it's important to not only manually install the semantic backends and add them to the config file, but to add `.cmd` at the end of the command. Instead of `which` you can use `where` in the CMD in order to find the correct paths.

Here's an example of a `TabNine.toml` for Javascript and CSS:
```
[language.javascript]
command = "C:\\Users\\yourusername\\AppData\\Roaming\\npm\\flow.cmd"
args = ["lsp"]
install = [["npm", "install", "-g", "flow-bin"]]

[language.css]
command = "C:\\Users\\yourusername\\AppData\\Roaming\\npm\\css-languageserver.cmd"
args = ["--stdio"]
install = [["npm", "install", "-g", "vscode-css-languageserver-bin"]]
```

**Comment by scholtes** [comment]
Just another example, if you are using Ruby under ChefDK on Windows, the following might work for you:

```
[language.ruby]
command = "C:\\opscode\\chefdk\\bin\\chef.bat"
args = ["exec", "solargraph", "stdio"]
install = [["C:\\opscode\\chefdk\\bin\\chef.bat", "gem", "install", "solargraph"]]
```

Though for posterity, I opted to manually run `chef gem install solargraph` and excluded the `install` line from my `TabNine.toml`.

**Comment by tgrades** [comment]
Why this is closed? Isn't it still a bug? At least give us an ability to set which shell to use. I have both `bash` and `sh`, but I assume it's trying to use `cmd` on windows, which no one is actually using...
