### ISSUE TITLE
when typing "TabNine:vesrion", error "no commands matching" occur

### ISSUE THREAD

**Issue by doyou89** [zxqfl/TabNine#113]
In the vscode, when I type "TabNine:vesrion" in "Show All Commands", "no commands matching" message displayed.

**Comment by Shougo** [comment]
TabNine::version is correct.

**Comment by shuxiao9058** [comment]
😂

**Comment by zxqfl** [comment]
You should type it into the file, like in this video: https://update.tabnine.com/v/enable_cloud.mp4
