### ISSUE TITLE
Establishing connection to TabNine Cloud is not completed

### ISSUE THREAD

**Issue by iasandcb** [zxqfl/TabNine#120]
On macOS Catalina (10.15 Beta 19A526h build), TabNine logs say:

[2019-08-02][08:09:59][lunar_transport::controller][ERROR] Error establishing SSL connection: The certificate was not trusted.
[2019-08-02][08:10:00][lunar_transport::controller][ERROR] Error establishing SSL connection: The certificate was not trusted.
...

**Comment by ACMLOSer** [comment]
I encountered the same problem, but it works well when I use macOS Mojave. I still can't fix it with my Catalina System. Is there a solution?

**Comment by randomnerd** [comment]
Having the same issue =(

**Comment by lynn** [comment]
Me too. Is it related to [this](https://www.macobserver.com/news/apple-deprecates-sha-1/)?

**Comment by iamakulov** [comment]
Catalina is out now! The issue reproduces for me:

> [2019-10-08][00:25:21][lunar_transport::controller][ERROR] Error establishing SSL connection: The certificate was not trusted.

**Comment by MichaelSchmidt82** [comment]
Can confirm this happens for me too after upgrading macOS to Catalina

**Comment by lemeb** [comment]
Can confirm tis. Does _not_ work in Sublime Text for me either...

**Comment by lemeb** [comment]
> Me too. Is it related to [this](https://www.macobserver.com/news/apple-deprecates-sha-1/)?

@lynn 

<img width="842" alt="Screen Shot 2019-10-20 at 16 56 02" src="https://user-images.githubusercontent.com/7331643/67166105-15dfe600-f37c-11e9-997d-61110dcc64b2.png">

I would doubt so, the certificate used by TabNine -- although self-signed -- is SHA-256, which means SHA-2 if I'm not mistaken

**Comment by phyllisstein** [comment]
I’m having the same issue in Atom and VSCode, under macOS 10.15. Here’s TabNine’s log:

```
[2019-10-23][20:42:49][lunar_transport::controller][INFO] Creating lunar client...
[2019-10-23][20:42:49][lunar_local::bridge][INFO] TabNine Local communication thread started.
[2019-10-23][20:42:49][lunar_local::bridge][INFO] TabNine Local is disabled; message forwarder is sleeping until config change...
[2019-10-23][20:42:49][lunar_transport::controller][INFO] Connecting to V4(35.226.242.34:7777)
[2019-10-23][20:42:49][lunar_transport::controller][ERROR] Error establishing SSL connection: The certificate was not trusted.
```

OpenSSL reports the certificate is indeed self-signed. Adding it to Keychain and telling the system to always trust it didn’t do me any good.

**Comment by theonlygusti** [comment]
This issue is months old.

It's November now, I still have this problem.

**Comment by phyllisstein** [comment]
I dropped @zxqfl an e-mail about it a couple weeks back, but haven't heard anything yet. As a TabNine Professional license-holder and an admirer of the project, I'd be super disappointed to see it lapse, unmaintained, into limbo.

**Comment by Shougo** [comment]
@zxqfl have replied some days ago.
Please read this.

https://github.com/zxqfl/TabNine/issues/179

**Comment by zxqfl** [comment]
Thanks for the report. The link from @lynn (https://www.macobserver.com/news/apple-deprecates-sha-1/) seems like a likely explanation, specifically this line:
> TLS server certificates must present the DNS name of the server in the Subject Alternative Name extension of the certificate. DNS names in the CommonName of a certificate are no longer trusted.

The TabNine Cloud certificate (which is embedded in the TabNine binary) has only a CommonName, not a Subject Alternative Name.

**Comment by Alpha-Monocerotis** [comment]
Well, I'm wondering when the problem will be fixed. @zxqfl

**Comment by Nyte-BK201** [comment]
Well, it has been long(3.5 months) after the problem arose but not having any solution which proves a project by individual workshop can be totally unreliable which frustrates me to no end.

**Comment by MisotheisticYHWH** [comment]
Well, after having just updated to Catalina it has become very clear to me how much of my workflow has become reliant on TabNine. I see that @zxqfl is extremely busy, which seems to be his reasoning for not addressing a known issue that breaks the product for all users on the GA release of MacOS.  I don't envy the position of developing something that gets such a huge reception. It clearly leaves people with more work than they can feasibly perform without hiring employees. Honestly, my expectation is that this is what will happen, but it usually ends up just being the on individual selling as many licenses as possible and then mismanaging the amazing product into the ground.

**Comment by MisotheisticYHWH** [comment]
@zxqfl  -- Is this on your roadmap to be fixed, or is it being put into the "known bug/no fix planned" bucket? This is only going to become a larger issue as more devs jump into Catalina (and the future versions of MacOS). I think the perceived impact may be smaller due to many devs not wanting to move forward into the the Catalina environment due to an enormous number of apps we depend on which also have issues with Catalina. But the progress is being made elsewhere,  so I would expect most projects will support Catalina within the year, or they'll be dead to the MacOS community (and NONE of us want that).

So @zxqfl, what's the plan? =)

**Comment by CraftLogan** [comment]
I am having the same problem. Looking forward to a solution because I love tab nine!

**Comment by drorweiss** [comment]
Thank you for reporting this problem. We will roll out a fix in the next few days. We are working hard to fix other pending issues at an accelerated pace. Starting in January 2020, the Codota team, together with @zxqfl, will be maintaining and improving TabNine to make sure this amazing project remains worthy of your trust.
--Dror Weiss (CEO @Codota)

**Comment by amircodota** [comment]
We released TabNine 2.2.0 that addresses this issue.
What we basically did was move away from the self signed certificate, and use Let's Encrypt certificates instead.

If you already have TabNine installed and have automatic updates turned on (which is the default), you should get the update pretty soon.
If you removed it, we'd love it if you re-install and give it another try.

Please let us know if you still encounter issues.

Thanks
Amir Tuval
Core Engineer @codota

**Comment by noahlh** [comment]
Great news!!  Thanks @amircodota and @drorweiss (and @zxqfl).

Just for the curious, reading between the lines:  Did Codota acquire TabNine?  Or?

**Comment by iasandcb** [comment]
I tried 2.2.0 out and found it working well!

Thanks for your great work so far.

**Comment by drorweiss** [comment]
@noahlh yes - Codota has acquired TabNine! We will post on Codota's and TabNine's blogs next week.
