### ISSUE TITLE
Sublime Text 3 on Windows: is the completion working?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [zxqfl/TabNine#122]
I can't tell whether the TabNine completion is working or not. I've had completion before I installed it, and it looks like what I'm getting now is precisely the same as before. Do I need to turn off the existing auto completer? I program in Julia, by the way.

Is there a test case that will show that TabNine is actually working?

**Comment by PetrKryslUCSD** [comment]
Oh, it took a restart. I turned off the auto completion
```
"auto_complete": true,
```
and restarted ST3. Then I installed TabNine. Now it seems to be working fine.

**Comment by zxqfl** [comment]
Great! The installation is supposed to turn off the setting but I guess it didn't work in this case.
