### ISSUE TITLE
user-provided custom LSP backends (a.k.a semantic completion)

### ISSUE THREAD

**Issue by pcr910303** [zxqfl/TabNine#127]
Currently TabNine only allows [`cquery`](https://github.com/cquery-project/cquery) for C/C++, [`flow`](https://flow.org) for JS, [`typescript-language-server`](https://github.com/theia-ide/typescript-language-server) for TS, e.g.
However, `cquery` is [unmaintained](https://github.com/cquery-project/cquery/issues/867)([`clangd`](https://clang.llvm.org/extra/clangd/)/[`ccls`](https://github.com/MaskRay/ccls) are competing in the space), `flow` only works (AFAIK) for `flowjs` code, the installation method `npm` used when installing `flow`, `typescript-language-server`, `html-languageserver`, `ocaml-language-server`, e.g. may not be preferred by users using `yarn`.

These kind of problems will persist as all computer environments are different, and (while providing good defaults are great)TabNine shouldn't decide a definite way to install/run LSP servers.

I would appreciate adding user-provided custom LSP backends.

**Comment by CarlQLange** [comment]
I think you may be incorrect. You can use different backends by configuring them like in [this document](https://www.tabnine.com/semantic) (which has an example of `ccls` instead of `cquery`).

**Comment by pcr910303** [comment]
@CarlQLange Oops; I should RTFM :-(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
