### ISSUE TITLE
(Atom) Allow autocomplete suggestions from other plugins

### ISSUE THREAD

**Issue by Zireael** [zxqfl/TabNine#133]
Hi,
I find TabNine handy for variable tips, but it completely suppresses autocomplete/snippet suggestions from other plugins, so I lose access to all snippets to scaffold functions/objects/templates.

I would be happy if TabNine had option to limit number of suggestions it gives, and also, allowed suggestions from other sources to show.
For JavaScript/Vue/HTML/CSS it isn't be-all end-all.

**Comment by zxqfl** [comment]
We don't want to suppress other autocompleters, but it seems to automatically happen as a result of TabNine registering itself as available for all languages. We can look into offering settings to disable TabNine in certain files. You could try the VS Code plugin which doesn't suppress other autocompleters.

**Comment by Zireael** [comment]
Thanks, It looks like I should be making an enhancement request to Atom package.
I'll check out VScode.
