### ISSUE TITLE
Option to disable autocomplete for code comments

### ISSUE THREAD

**Issue by duncancarroll** [zxqfl/TabNine#140]
While I find TabNine to be very useful for code, the autocomplete is not useful when writing comments, and just adds unwanted noise.

Recommend adding a feature which allows disabling of autocomplete after a comment prefix is detected (`// <!--, #`) etc.  Would be best if this were enabled (i.e. comments are not autocompleted) by default!

**Comment by zxqfl** [comment]
I've added to the backlog a task to make completion more conservative in comments.

**Comment by uolot** [comment]
I think this is already implemented, but perhaps doesn't work for all cases? I don't get completions in comments when writing Python code in Vim with TabNine.

**Comment by narnianpony** [comment]
Issue stille happenning on PHP using multilne comments for functions documentation. Eg:
/*
*  this should not autocomplete
*/

**Comment by ThatWeirdAndrew** [comment]
This still happens when writing Python in PyCharm.

**Comment by pychap** [comment]
I would _really_  appreciate being able to remove auto-suggestions from comments, it can be quite frustrating, annoying. Would be nice if a script could be written into user preferences for this.

**Comment by Dezzymei** [comment]
+1

**Comment by Smitty010** [comment]
+1.  Being "more conservative" is not likely to help until you have an ESP chip.  I would like to turn them off.

**Comment by filipejunqueira** [comment]
Can we please implement this on Python (using Pycharm). My god it is annoying. It is the only reason why I don't use tabnine. It's a nightmare if you want your code to be well documented.

**Comment by stramin** [comment]
Autocompletion in comments is a annoying, but that's not all, I am also getting autocompletion for code obtained from what I've written in comments, which is also annoying.

**Comment by tr3ysmith** [comment]
Why is this closed?!? This is getting so annoying and it's happening in Rust as well. As a paid service, I'm also considering cancelling, because its slowing me down just to comment my own code...

**Comment by pbower** [comment]
I cannot stand Tabnine constantly auto completing comments.
