### ISSUE TITLE
Allow ignoring certain folders/extensions

### ISSUE THREAD

**Issue by pirate** [zxqfl/TabNine#15]
For many projects, `.gitignore` is not enough, we also want to explicitly ignore certain folders of autogenerated code while keeping them in version control.

For example, in our project we have:

```jsx
client/
    js/
        vendor/
             ...       // we want to ignore everything in here, but keep it in our VCS

server/
    build/
        ...            // we also want to ignore all autogenerated code in here, while keeping it in our VCS
    src/
        ...            // but we do want to autocomplete any files from here

```

**Suggested Fix:**
Allow adding a `.tabnineignore` file, just like `.gitignore`, `.dockerignore`, `.npmignore`, etc.
This can be excluded from VCS or added, it's up to the user.

**Comment by zxqfl** [comment]
tabnineignore will be added in the next release. In the meantime, you could try adding a .ignore file.
