### ISSUE TITLE
Adding context to the autocomplete: adding the copy buffer and the line number?

### ISSUE THREAD

**Issue by vincentdesmares** [zxqfl/TabNine#151]
Hi everyone. 

Many times I'm copy/pasting a package name that I want to import to after typing : "import ....".

It would be awesome to include the copy buffer to the scope of the autocomplete so that it adds even more context to the proposals.

**Example:**

If I have **"useSelector"** in my copy buffer. I expect **"import { useSelector } from 'react-redux'"** to be one of the top autocomplete for a blank line autocomplete or an "imp" string.

**Another related suggestion:**

Right now blank-line autocomplete returns nothing. Yet it could be powerful with a bit more context like the line number. When I'm autocompleting at the top of my files it will mostly be an import.

What are you thinking about those features?

**Comment by zxqfl** [comment]
I'll add your line number suggestion to the backlog. I agree showing the model the copy buffer could be quite useful, but I don't see a way to get training data to teach the model to use it effectively.
