### ISSUE TITLE
Downgrading the binary

### ISSUE THREAD

**Issue by jaydorsey** [zxqfl/TabNine#154]
How do I get an old version of the binary?

I paid for a license. The last version that worked "as expected" for me was around 1.10.0-ish. I'd like to revert to the older binary.

I can't download the older binary directly via the updates.tabnine.com URL. Can these be republished?

**Comment by jaydorsey** [comment]
This one: https://update.tabnine.com/1.10.0/x86_64-apple-darwin/TabNine

I get a 403 with that URL. Swapping out the version for 2.1.17 I can download latest

**Comment by zxqfl** [comment]
Try https://update.tabnine.com/1.0.14/x86_64-apple-darwin/TabNine <https://update.tabnine.com/1.0.14/x86_64-apple-darwin/TabNine> (last version before 2.0.0)

**Comment by jaydorsey** [comment]
That seems to have worked, thanks. I'll give that one a shot. Testing it to see if it resolves my other issue w/ the suggestions
