### ISSUE TITLE
With Rust completion pops up after typing a semicolon

### ISSUE THREAD

**Issue by burjui** [zxqfl/TabNine#159]
Since we usually press `Enter` after a semicolon, the suggestion is immediately inserted, so I have to press `Escape` after every semicolon.

**Comment by burjui** [comment]
Actually, the same happens after typing any kind of bracket: `{`, `}`, `(`, `)`, `[`, `]`, `<`, `>`

**Comment by zxqfl** [comment]
Most editors allow you to disable using Enter to accept completions — if you use VS Code or Atom, please try the instructions at https://tabnine.com/install/.

**Comment by burjui** [comment]
Oh, sorry, forgot to mention that I'm using IntelliJ IDEA.
