### ISSUE TITLE
Switch from cquery to clangd as a default C/C++ language server

### ISSUE THREAD

**Issue by JanPokorny** [zxqfl/TabNine#161]
# cquery
- not maintained for over a year
- not available in any package manager
- not even binary releases available, huge hassle to install

# clangd
- part of LLVM/Clang suite, many C++ developers have already installed
- multiplatform
- easily installed through package managers by a single command
- actively developed

# Proposed change

Change the default language server to clangd. It works out of the box like this:

```ini
[language.cpp]
command = "clangd"
args = []
```

**Comment by Shougo** [comment]
I have tested and I think clangd is better than cquery.

The PR is created.
