### ISSUE TITLE
Error saving changes during the activation

### ISSUE THREAD

**Issue by ShaneDean** [zxqfl/TabNine#169]
I got an error in using my Activation key;

**Error saving your changes: there was an error contacting tabnine.com: https://api.tabnine.com/api_key_info/v1: error trying to connect: unexpected EOF during  handshake**

TabNine IntelliJ plugin  v0.1.3 
IntelliJ IDEA 2019.1.2 (Ultimate Edition)

I put the URL in browser and got a 404.

what should I do next?

**Comment by louizo** [comment]
same for me
seems api server is down?
`[2019-10-14][09:27:28][lunar_local::downloader][ERROR] https://api.tabnine.com/model_metadata/v1: error trying to connect: Hôte inconnu. (os error 11001)`

same for key activation:
`Error saving your changes: there was an error contacting tabnine.com: https://api.tabnine.com/api_key_info/v1: error trying to connect: Hôte inconnu. (os error 11001)
`

**Comment by zxqfl** [comment]
`api.tabnine.com` is currently up, please comment if the issue persists.

**Comment by heavenkiller2018** [comment]
I have the same problem  after typing Activation key received from email! what should I do next?
Error saving your changes: there was an error contacting tabnine.com: https://api.tabnine.com/api_key_info/v1: error trying to connect: unexpected EOF during handshake

**Comment by amircodota** [comment]
Hi @heavenkiller2018 

Are you behind a corporate proxy or a firewall?

**Comment by juzi5201314** [comment]
Hi, I am from China. Because of China's special network, I directly connect api.tabnine.com and update.tabnine.com and get timeout.
But I use proxy, it will "error trying to connect: unexpected EOF during handshake" and Browser 404

**Comment by 2234839** [comment]
I have the same problem
`
Error saving your changes: there was an error contacting tabnine.com: https://api.tabnine.com/api_key_info/v2: error trying to connect: unexpected EOF during handshake
`

**Comment by SeanWit** [comment]
The same problem
Error saving your changes: there was an error contacting tabnine.com: error sending request for url (https://api.tabnine.com/api_key_info/v2): operation timed out

**Comment by mtrucc** [comment]
Hi, I am from China. Because of China's special network, I directly connect api.tabnine.com and update.tabnine.com and get timeout.
But I use proxy, it will "error trying to connect: unexpected EOF during handshake" and Browser 404

**Comment by dimacodota** [comment]
Hi @mtrucc , what OS are you using? did you set the proxy environment variables (HTTP_PROXY and HTTPS_PROXY in case of Linux)?

**Comment by mtrucc** [comment]
Windows 10
I set HTTP_PROXY in System settings。
Because China has the Great Firewall, I must use a proxy to access github google normally
[Great_Firewall](https://en.wikipedia.org/wiki/Great_Firewall)

**Comment by dimacodota** [comment]
do you mean Settings → Network & Internet → Proxy? 
you need to set the https proxy as well

**Comment by mtrucc** [comment]
> do you mean Settings → Network & Internet → Proxy?

Yes

How should I set it, the address I filled in 127.0.0.1
