### ISSUE TITLE
Any plan to release a roadmap?

### ISSUE THREAD

**Issue by cyc115** [zxqfl/TabNine#17]
Hi there! First I would like to thank you for your wonderful auto-completer. I've been trying it out for the last couple of days and it works well. Is there any plan to release a roadmap or backlog for the development of this plugin?

**Comment by nblackburn** [comment]
This is needed especially now the price has gone up.

**Comment by zxqfl** [comment]
Here's what's planned for the near future: https://tabnine.com/blog/future
