### ISSUE TITLE
No semantic completion backends work.

### ISSUE THREAD

**Issue by Reisen** [zxqfl/TabNine#18]
I've tried several completion backends and all result in the same popup:

![image](https://user-images.githubusercontent.com/158967/48848160-2f0e9a00-ed9b-11e8-853a-246c1fa478d2.png)

I have tried JavaScript with the default settings, with `flow` pre-installed and removing the install command, removing the install command and using `/usr/local/bin/flow` as an absolute path for `command`. I've tried `hie` in a stack repo, in both subdir files and `Setup.hs` at the project root. I've also run `hie` and `flow` alone and they run fine if started manually.

I'd like to debug this, but without stdout/stderr logged somewhere useful I don't know how to debug this short of trying to ptrace the binary, but don't have time right this moment.

**Edit**: This is on MacOS, within MacVim using the YCM fork vim plugin.

**Comment by Reisen** [comment]
Never mind I'm just an idiot. MacVim has a path issue, works in terminal.

As an aside, absolutely loving TabNine so far, thanks for the awesome work!

**Comment by aurnik** [comment]
Hey @Reisen how were you able to get this to work? I'm on OS X as well using Terminal and I tried default settings for JavaScript, tried installing `flow-bin` globally, but I still get a similar error except the command that failed was `npm install -g flow-bin`

**Comment by robot110011** [comment]
@aurnik just use command = "/usr/local/bin/flow" as @Reisen and it should work.
