### ISSUE TITLE
C++ function suggestion wrong.

### ISSUE THREAD

**Issue by KazDelphi** [zxqfl/TabNine#196]
![2019-11-16 11-33-09屏幕截图](https://user-images.githubusercontent.com/27542299/68987585-ebdbef80-0865-11ea-9a77-7d7c9a903fd0.png)
'L' not 'l'!

**Comment by amircodota** [comment]
Hi @KazDelphi 

Sorry it took so long to get back to you.
Can you explain what were you expceting to see?

**Comment by KazDelphi** [comment]
![tabn](https://user-images.githubusercontent.com/27542299/72340696-9906a300-3703-11ea-8d89-5fbc936bc99c.png)
Sorry I forget to upload image...
This is C++Code.
The letter 'l' should be 'L'.

**Comment by amircodota** [comment]
Sorry, I'm not sure I understand.

You typed "loca", right?

TabNine suggests a few suggestions, all starting with the lower case 'l'.
Were you expecting upper case "L"? Why?

**Comment by KazDelphi** [comment]
![tabn](https://user-images.githubusercontent.com/27542299/72341495-61005f80-3705-11ea-9491-8e8d0ac70303.png)
These functions all start with "L",but Tabnine displays 'l'

**Comment by amircodota** [comment]
As it stands, TabNine does not try to do semantic validation on its predictions.
Because of that, it may suggest something that will not compile on occasion.
We are working on adding semantic validation on our predictions, so things should improve in the future.

**Comment by KazDelphi** [comment]
Thank you.
