### ISSUE TITLE
Provide some central source for binaries so I can write my own Vim plugin

### ISSUE THREAD

**Issue by tbodt** [zxqfl/TabNine#2]
The Vim plugin is based on YouCompleteMe, which I can't use because it conflicts with my other autocompleting plugin (deoplete). I would happily write my own plugin (deoplete source) but the main thing preventing me from doing that is no central source for binaries; instead they're included in the git repo (which also means you have to download every version of every binary for every platform when you install the plugin.)

Could there be some documentation provided for update.tabnine.com?

**Comment by zxqfl** [comment]
I'm happy to hear you're considering writing your own plugin! I added a script to download the binaries. I'll write a guide for creating clients within a couple of days.

**Comment by tbodt** [comment]
Thanks! I've got one more question: there seems to be 3 different protocols for communicating with TabNine (sublime, vscode, vim). Is there any difference between the feature set available through the different protocols?

**Comment by zxqfl** [comment]
Sublime and VS Code are actually the same protocol. I recommend you use that one as it supports substituting characters after the cursor (eg. if there is () after the cursor and the completion ends in (), it will delete the () after the cursor).

**Comment by tbodt** [comment]
Got the plugin working: https://github.com/tbodt/deoplete-tabnine. I'm having some issues with it not updating when you press a key though, seems to be due to the design of deoplete.

**Comment by zxqfl** [comment]
Great! Sublime also had that issue, it's why I wrote the plugin to bypass the autocomplete API. It looks like the `is_volatile` option might fix the issue? https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt

Let me know if you sort out the issue, I would consider making this the official Vim plugin as the existing plugin is quite heavyweight. (It is forked from YouCompleteMe and contains lots of code that isn't used.)

**Comment by tbodt** [comment]
I tried is_volatile, and also rerunning the completion from on_post_filter, and that didn't help much. The most likely solution is probably to open an issue on deoplete.

**Comment by tbodt** [comment]
https://github.com/Shougo/deoplete.nvim/issues/869

**Comment by Shougo** [comment]
I have started to use deoplete-tabnine.

**Comment by tbodt** [comment]
https://github.com/Shougo/deoplete.nvim/pull/812 enabled refresh_always by default, and since then the plugin works fine.
