### ISSUE TITLE
TabNine doesn't work in new Intellij 2019.3

### ISSUE THREAD

**Issue by d2a-raudenaerde** [zxqfl/TabNine#200]
This is the error: 08:36	Plugin Error: Plugin "TabNine" is incompatible (target build range is 162.* to 192.*).

**Comment by a-sane** [comment]
I found a workaround:

1. download tabnine plugin zip file
2. unzip it
3. unzip TabNine-0.1.3.jar file inside
4. edit  META-INF/plugin.xml file – change until-build attr to "193.*"
5. make new jar archive with edited file and install plugin manually to Intellij

**Comment by d2a-raudenaerde** [comment]
@a-sane Thanks for you reply.. Sounds easy enough to patch.

Where do I download the plugin-zip? I can't find it here nor in the tabnine-intellij repo?

**Comment by a-sane** [comment]
@d2a-raudenaerde https://plugins.jetbrains.com/plugin/12798-tabnine/versions

**Comment by matheussousaf** [comment]
Is that solution working for you guys? Just did it and TabNine didn't worked in my IDEA IntelliJ 19.3

**Comment by a-sane** [comment]
@matheussousaf works well in my WebStorm 2019.3

**Comment by DPS0340** [comment]
my IntelliJ 2019.3 using jar file made by https://stackoverflow.com/questions/18146361/how-to-create-jar-file-with-package-structure it works well. Thanks!

**Comment by amircodota** [comment]
TabNine now supports all 2019.3 JetBrains IDEs.
Closing.

Feel free to re-open if you still encounter issues
