### ISSUE TITLE
TabNine automatically sets auto_complete to false, without any notice

### ISSUE THREAD

**Issue by Ornataweaver** [zxqfl/TabNine#204]
This is the email I sent to another extension development team:
"
I fount the fucking bug. (sorry for being rude, I'm angry.)TabNine extension, when enabled, automatically sets
 "auto_complete": false,
in Preferences.sublime-settings
without any notice.

It took me more than 6 hours. I thought it was because of my other poor extensions! #ThinkOutofTheBox
However I still find TabNine extremely useful.
"
Thank you for your efforts, but a simple ignorance can cause 6 hours of debugging in many devs schedule.

**Comment by amircodota** [comment]
Hi @Ornataweaver And sorry it took a while to get back to you.

Unfortunately, sublime's builtin autocomplete does not support all the features required by TabNine, and so we were forced to replace it with something custom made.
This is definitely something we may re-visit in the future, but for now, that is the way it works.

I've added a note to TabNine's sublime plugin README, in the hope it will prevent other people from wasting time in the future.
