### ISSUE TITLE
TabNine stopped working

### ISSUE THREAD

**Issue by ArashHosseini** [zxqfl/TabNine#207]
Hi @zxqfl, 
thanks for your work, Tabnine is the future and has huge potential, I can not work without it but I have following problem: 
It stopped working suddenly on two different machines independently of each other. The Tabnine process does not start when I start sublime and consequently no auto completion. I have reinstalled Sublime and Tabnine but no change. Did I miss something or how i can fix that?
thx

**Comment by ThomasAitken** [comment]
Not just you. It's disappeared even as a package in Package Control on Sublime...

**Comment by tjd** [comment]
TabNine also just stopped working for me in Sublime on Ubuntu. Re-installing Sublime and TabNine doesn't seem to make a difference. I get this error in the console:
reloading plugin TabNine.TabNine
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/snap/sublime-text/85/opt/sublime_text/sublime_plugin.py", line 610, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/home/tjd/.config/sublime-text-3/Packages/TabNine/TabNine.py", line 334, in on_selection_modified_async
    response = tabnine_proc.request(request)
  File "/home/tjd/.config/sublime-text-3/Packages/TabNine/TabNine.py", line 89, in request
    self.restart_tabnine_proc()
  File "/home/tjd/.config/sublime-text-3/Packages/TabNine/TabNine.py", line 85, in restart_tabnine_proc
    startupinfo=get_startup_info(sublime.platform()))
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1370, in _execute_child
  File "./python3.3/os.py", line 791, in fsencode
TypeError: expect bytes or str, not NoneType

**Comment by theol0403** [comment]
I am getting the exact same problem with the same console error. Reinstalling the sublime package did not solve the problem.
Looks like there is some more information with a fix here:
https://github.com/zxqfl/tabnine-sublime/issues/48

**Comment by ArashHosseini** [comment]
thx, solved by aiming to `/home/<user>/.config/sublime-text-3/Packages/TabNine/binaries/2.1.22` directory, renaming `x86_64-unknown-linux-gnu` to `x86_64-unknown-linux-musl` and restarting sublime

**Comment by Coder2011-ALT** [comment]
My tabnine stopped working and it is showing 'TabNine.statusBar Not found.'
