### ISSUE TITLE
Why the indexing limit?

### ISSUE THREAD

**Issue by WorldSEnder** [zxqfl/TabNine#3]
Even the Premium version of TabNine is advertised with a limit of "Up to 15 MB indexed".

I understand that for most smaller projects that's sufficient. But looking at the sources of Blender or the Linux kernel as bigger, but still reasonable projects it is evident that this restriction is somewhat too small.

This makes me think that there are some hidden performance problems when running on such large code bases. For example, will the code completion persist any indexing it does to disk?

Since the free version supports only 200 KB of files I can hardly do any testing. Do you have any solid benchmarks to show where the completion runs on larger projects?

**Comment by zxqfl** [comment]
TabNine does not persist anything to disk.

All versions of TabNine still work with projects larger than the indexing limit. Files will be added and removed from the index to ensure that the indexed files are as relevant as possible to the files you are editing.

I added a 30-day money back guarantee for the paid version.

The limit exists to ensure low latency for autocompletions. Based on my experience you can expect 50 ms to be an upper bound even for large projects. Of course, your mileage may vary (hence the 30-day guarantee).

**Comment by zxqfl** [comment]
TabNine does not persist anything to disk.

All versions of TabNine still work with projects larger than the indexing limit. Files will be added and removed from the index to ensure that the indexed files are as relevant as possible to the files you are editing.

I just added a 30-day money back guarantee for the paid version.

The limit exists to ensure low latency. Based on my experience, 50 ms is an upper bound even for large projects. Of course, your mileage may vary (hence the 30-day guarantee).

**Comment by zxqfl** [comment]
TabNine does not persist anything to disk.

All versions of TabNine still work with projects larger than the indexing limit. Files will be added and removed from the index to ensure that the indexed files are as relevant as possible to the files you are editing.

I just added a 30-day money back guarantee for the paid version.

The limit exists to ensure low latency. Based on my experience, 50 ms is an upper bound even for large projects. Of course, your mileage may vary (hence the 30-day guarantee).
