### ISSUE TITLE
after setting up tabnine i cannot use <C-x> <C-f> any more for filepath completion is there any work around?

### ISSUE THREAD

**Issue by NikosEfthias** [zxqfl/TabNine#31]

**Comment by Shougo** [comment]
You should upload more information to reproduce.

**Comment by Shougo** [comment]
It seems tabnine-vim's(YCM's) problem.
The auto completion plugin conflicts with manual completion(filename completion, line completion).

**Comment by NikosEfthias** [comment]
@Shougo is there any workaround ? i had to disable tabnine because of this

**Comment by NikosEfthias** [comment]
TabNine file completion unfortunately doesnt work. Or at least the directory listing is not working
![gif](https://user-images.githubusercontent.com/9097437/49883711-bf954300-fe4c-11e8-9ca6-3c8745af9a57.gif)

**Comment by NikosEfthias** [comment]
for a brief second the popup is there then its closing

**Comment by zxqfl** [comment]
This looks like it could be a conflict between completion plugins. Can you provide steps to reproduce the issue?

**Comment by NikosEfthias** [comment]
I can't, unfortunately. I stopped using tabnine after this which was a year ago
