### ISSUE TITLE
TabNine wants to access my contacts and calendar

### ISSUE THREAD

**Issue by Npahlfer** [zxqfl/TabNine#33]
I recently got these two messages telling me that TabNine wants to access my contacts and calendar.
That sounds a bit creepy if you ask me, could you explain to me why TabNine would want to do that?

![screenshot 2018-12-06 at 07 29 40](https://user-images.githubusercontent.com/1068840/49565909-2b494e80-f929-11e8-84ef-87d4d952d442.jpg)
![screenshot 2018-12-06 at 07 29 52](https://user-images.githubusercontent.com/1068840/49565911-2be1e500-f929-11e8-9eb4-a09d983d2b1e.jpg)

**Comment by zxqfl** [comment]
TabNine does not need your contacts or calendar, so feel free to press "Don't Allow". My best guess for why this is happening is that in the course of walking your project directory, it ended up in the contacts or calendar folders, and then its attempts to index those directories were interpreted by OSX as asking for your personal information.

Sorry for the popup.

**Comment by Npahlfer** [comment]
Thanks, that sounds like it could be the case, I was in my home directory while it happened.
