### ISSUE TITLE
Feature request for customizing go lsp

### ISSUE THREAD

**Issue by cosmtrek** [zxqfl/TabNine#49]
Golang server is a bit slow, I want to try [bingo](https://github.com/saibing/bingo). Could you support this option in config file? Thanks!

**Comment by zxqfl** [comment]
Hi cosmtrek, have you seen https://tabnine.com/semantic? There's an example of overriding the default config to use `ccls` which you could adapt to use bingo.

**Comment by cosmtrek** [comment]
Thanks a lot!
