### ISSUE TITLE
Support nested Git repositories

### ISSUE THREAD

**Issue by zxqfl** [zxqfl/TabNine#5]
```
root
|
|-- subproj1
|
|-- subproj2
    |
    |-- subsubproj1
    |
    |-- subsubproj2
```
Currently TabNine will stop at the first `.git` it finds, but it should continue to try to find a `.tabnine_root`.

**Comment by trishume** [comment]
Watch out, some people have their home directory as a git directory for dotfiles purposes. I think this is a bad idea but in nevertheless happens and might be worth a special case to avoid.

**Comment by zxqfl** [comment]
This should be fine -- we still stop at the first `.git`, we only keep looking for a `.tabnine_root`. (So users with nested Git repos need to put a tabnine_root in the parent repo.)
