### ISSUE TITLE
Question regarding --client options and protocol version

### ISSUE THREAD

**Issue by superDuperCyberTechno** [zxqfl/TabNine#53]
1. In the Sublime client you pass the parameter [`--client=sublime`](https://github.com/zxqfl/tabnine-sublime/blob/master/TabNine.py#L81). What is the purpose of this? I cannot locate any such a parameter in the Vim client...

2. In [HowToWriteAClient.md](https://github.com/zxqfl/TabNine/blob/master/HowToWriteAClient.md) you write the following:

_The protocol is versioned. The protocol versions are the same as TabNine versions. To guarantee forward compatibility with future versions of TabNine, pass the current TabNine version (or any previous version) as the protocol version._

Can you elaborate on this? What exactly is the mechanics? It's especially puzzling [as the Sublime client uses a hardcoded version of 1.0.0](https://github.com/zxqfl/tabnine-sublime/blob/master/TabNine.py#L107). Shouldn't it be set to the latest TabNine version (1.0.10 as of writing)?

**Comment by zxqfl** [comment]
Hi,

1. The parameter isn't used for anything at the moment. I probably won't use it in the future either, but adding it seemed like a good precaution at the time.

2. A version of 1.0.0 is the system working as intended. This way, if I release TabNine 2.0 and it has a completely new protocol, it can still talk to the Sublime client by falling back to the old version (which is possible because the Sublime client identifies itself as expecting the old version).

**Comment by superDuperCyberTechno** [comment]
2. So what you're saying is that the protocol version is actually versioned independently of the TabNine binary version? Or will queries with version 1.0.0 be redirected to version 1.0.0 of the binary (that is then downloaded if doesn't exist)?

**Comment by zxqfl** [comment]
The versions aren't independent (the current protocol version is always the binary version) but there's no new binary downloaded: every TabNine binary knows how to communicate using the protocol of every earlier binary.

**Comment by superDuperCyberTechno** [comment]
So convention should always be latest binary version. Wouldn't it be an idea then to have the protocol version always follow the latest binary version dynamically instead of hardcoding it?

**Comment by zxqfl** [comment]
The binary auto-updates itself. The reason it's designed this way is that if the client hasn't been updated yet, it might be unable to communicate using the newest protocol. So this lets us update TabNine (for example, to improve functionality independently of the protocol) without updating all 7 clients that depend on it.
