### ISSUE TITLE
Support for puresript

### ISSUE THREAD

**Issue by xgrommx** [zxqfl/TabNine#55]
Hello @zxqfl do u have some plan to add support for purescript (lsp already exists)?

**Comment by zxqfl** [comment]
Added -- you can wait for the next TabNine release or add the [relevant entry](https://github.com/zxqfl/TabNine/blob/849fb09abf6a0515d742bb6f732c37b2fa0704e3/TabNine.toml#L64) to your TabNine.toml right now [how to find TabNine.toml](https://tabnine.com/semantic)
