### ISSUE TITLE
LSP language misidentified as "Makefile"

### ISSUE THREAD

**Issue by orip** [zxqfl/TabNine#56]
I tried configuring TabNine with an LSP server for D.

Looking at [language_tokenization.json](https://github.com/zxqfl/TabNine/blob/3422bec600b88fe5d5e1e2401167947f059acea2/language_tokenization.json) I figured out that the mapping of supported languages is possibly hard-coded and stale, but the error messages I got when trying to enable semantic completion kept referring to Makefile for some reason.

```
...
Or, type TabNine::no_sem to disable semantic completion for Makefile.
```

`tabnine_config.json` also seems to misidentify my D files as makefile:

```
...,"semantic_status":{"makefile":"Enabled"},
```

**Comment by zxqfl** [comment]
Thanks for the report, this will be fixed in the next release.
