### ISSUE TITLE
Provide keyboard shortcut to close tabnine auto complete window

### ISSUE THREAD

**Issue by dotnetdanny** [zxqfl/TabNine#59]
Firstly, cracking plugin! I use this in vim and it has transformed the way in which I develop! Nice one!

This issue is to recognise the lack of a keyboard shortcut (I use Vim 8) to close the auto complete window. In Visual Studio products, the shortcut is (esc) although, this takes me out of Insert mode and even at that, the auto complete window still does not close until I press any other key. 

The ability to close or hide the auto complete window would allow me entire visibility of the code I am editing again so I can gently stroke my beard and think carefully of my next bold code change!

**Comment by Shougo** [comment]
It is not tabnine issue.
It seems Tabnine-vim issue.

https://github.com/zxqfl/tabnine-vim/issues

**Comment by dotnetdanny** [comment]
Ah, sorry, right you are. I have closed the issue and will reopen one against tabnine-vim :)

**Comment by dotnetdanny** [comment]
I have opened up https://github.com/zxqfl/tabnine-vim/issues/20 against tabnine-vim. Thanks
