### ISSUE TITLE
Make case conversion suggestions appear after suggestions from the project

### ISSUE THREAD

**Issue by zxqfl** [zxqfl/TabNine#6]

**Comment by neculaesei** [comment]
Awesome product! I just want to add that it would be awesome to disable snake/camel case suggestions (fx. there are many projects that don't use snake case at all)

**Comment by nblackburn** [comment]
I would suggest making this an option or at least suggesting intelligently based on the conventions of the file/project/language.

**Comment by zxqfl** [comment]
Closing this issue with a goal of detecting the project's case conventions more intelligently in the future.
