### ISSUE TITLE
protocol suggest

### ISSUE THREAD

**Issue by shuxiao9058** [zxqfl/TabNine#61]
I suggest that  the operation in json should with the same key, like `method`.

for example of autocomplete the request should be:

``` json
{"version":"x.0.0","request":{"method":"Autocomplete","before":"Hello H","after":"","region_includes_beginning":true,"region_includes_end":true,"filename":null}}
```

**Comment by zxqfl** [comment]
That does sound like a more intuitive API, but there are already clients using the current API, so there doesn't seem to be a strong reason to change it.
