### ISSUE TITLE
can not work with gopls

### ISSUE THREAD

**Issue by shuxiao9058** [zxqfl/TabNine#63]

**Comment by Shougo** [comment]
It works.  But...

* You need to install `gopls`
* You must enable tabnine semantic completion in go files
* `gopls` only works under `GOPATH` projects
* The latest version of `gopls` may not work(it seems gopls problem)

**Comment by shuxiao9058** [comment]
done, the problem is that the latest gopls not work,waiting...

**Comment by Shougo** [comment]
The latest version of gopls works.

**Comment by shuxiao9058** [comment]
> The latest version of gopls works.

yes, but gopls also failed with lsp-mode in emacs.

**Comment by Shougo** [comment]
Oh...
It is lsp-mode's problem?

**Comment by shuxiao9058** [comment]
maybe

**Comment by Shougo** [comment]
So it is not tabnine issue.
The issue should be closed.
