### ISSUE TITLE
Can you tell us the development plan of TabNine?

### ISSUE THREAD

**Issue by shuxiao9058** [zxqfl/TabNine#66]

**Comment by shuxiao9058** [comment]
sent an email to @zxqfl , but no reply.

**Comment by dynamix** [comment]
> Since TabNine has no externally imposed deadlines, I will impose one on myself: I intend to build this functionality by the end of January 2019, and release it to the public by the end of February.  [...] To get notified when I succeed or fail at this goal, subscribe to this blog.



Bought TabNine and subscribed to the blog and would appreciate an update as well 😄.

**Comment by shuxiao9058** [comment]
> > Since TabNine has no externally imposed deadlines, I will impose one on myself: I intend to build this functionality by the end of January 2019, and release it to the public by the end of February.  [...] To get notified when I succeed or fail at this goal, subscribe to this blog.
> 
> 
> 
> Bought TabNine and subscribed to the blog and would appreciate an update as well 😄. 

always waiting new feature.

**Comment by shuxiao9058** [comment]
I want to refund now.

**Comment by dynamix** [comment]
@zxqfl an update would be appreciated as it has been a while - even if it's "Sorry I don't have any time for this project anymore". I was quite excited back then when I read your blog post and bought TabNine.

> Since TabNine has no externally imposed deadlines, I will impose one on myself: I intend to build this functionality by the end of January 2019, and release it to the public by the end of February

**Comment by zxqfl** [comment]
Hi Martin,

TabNine is still being developed. Given the fate of the previous deadline, I won't give any specific timeline, but I'm excited about the new features under development and hope you will consider the wait to be worth it when they are released.
