### ISSUE TITLE
Fast flickering in gvim

### ISSUE THREAD

**Issue by davidnash** [zxqfl/TabNine#67]
Occasionally when using the vim plugin TabNine kind of "freaks out" and the suggestion list flickers - as if it's reloading the suggestions in an infinite loop. 

This happens when I'm editing a line (ie there's characters after the suggestion box):

![Peek 2019-04-09 10-36](https://user-images.githubusercontent.com/274968/55765493-61533680-5ab3-11e9-92c7-2e6888e18d58.gif)

The flickering occurs much faster than the GIF frame rate, but this should give you an idea.

(Also - this is such an awesome plugin! I absolutely love it!)

**Comment by Shougo** [comment]
Hm.. It seems YCM problem.
You can try deoplete-tabnine instead.
https://github.com/tbodt/deoplete-tabnine

**Comment by davidnash** [comment]
Thanks for the quick response.

Though I'd prefer not to use deoplete - I'm on vim8 and one of the dependancies is marked "experimental".

**Comment by zxqfl** [comment]
Do you have any custom YCM settings enabled?

**Comment by davidnash** [comment]
I don't - in fact I wasn't even aware TabNine used YCM, until @Shougo suggested using deoplete.

I'm going to try disabling all my other plugins just to see what happens - I'll let you know.

**Comment by davidnash** [comment]
Okay, it took a while to track down, but the issue occurs when TabNine is used in combination with [vim-matchup](https://github.com/andymass/vim-matchup).

I'm going to leave vim-matchup disabled for now. TabNine is much more valuable to me. I'm constantly impressed by how good its suggestions are.

**Comment by zxqfl** [comment]
I'm glad to hear it! Thanks for investigating -- I'll keep this in mind in case anyone else encounters the same issue.
