### ISSUE TITLE
Instructions / Support for using TabNine with coc.nvim

### ISSUE THREAD

**Issue by lovesegfault** [zxqfl/TabNine#71]
I was wondering how/if it would be possible to use TabNine integrated with CoC.nvim.

**Comment by chasote** [comment]
I was thinking the same as I just discovered TabNine. Unfortunately it seems to prevent the awesome ability to see the definitions of autocompletion suggestions that coc.nvim provides through it's floating windows. I will continue to monitor as this does seem like a cool project!

**Comment by yutakatay** [comment]
https://github.com/neoclide/coc-tabnine
