### ISSUE TITLE
How to register?

### ISSUE THREAD

**Issue by jedisct1** [zxqfl/TabNine#79]
I bought a license, saved the key, but not the instructions.

What is the command to get TabNine to parse the key?

**Comment by zxqfl** [comment]
Hi jedisct1. You can activate TabNine by pasting the key into your editor (including the `=== BEGIN TABNINE KEY ===` part) and then typing into your editor. TabNine will detect the key as part of the completion context and activate automatically.

**Comment by zxqfl** [comment]
Here are the full instructions:

1. If you haven't installed TabNine, follow the installation instructions to do so.
2. Open a new file in your text editor and verify that TabNine is running by typing TabNine::version. (You should type it in the file directly, not as a command to your editor.) If TabNine is working properly, you will see an autocompletion suggestion with TabNine's version.
3. Paste your registration key into the file.
4. Type TabNine::active. If everything worked, you should see the the suggestion 'Yes'.
