### ISSUE TITLE
TabNine should not index files in .git

### ISSUE THREAD

**Issue by zxqfl** [zxqfl/TabNine#8]

**Comment by sergei-dyshel** [comment]
Ultimately it would be nice to have some ignore file (e.g. `.tabnine.ignore`) and combine it with .gitignore, like Rigpgrep does.

**Comment by zxqfl** [comment]
This is actually already implemented, you can create an `.ignore` file.

**Comment by sergei-dyshel** [comment]
I would rather prefer to have it different name, since `.ignore` is used by grep-like  tools (`ack`, `ripgrep` etc.). I think TabNine-specific ignore file may ignore stuff which still need to be grepped...

**Comment by sergei-dyshel** [comment]
configurable name would be the best...

**Comment by BurntSushi** [comment]
The `.ignore` file is supposed to be somewhat generic. ripgrep also supports a `.rgignore` file, and if TabNine is using the `ignore` crate, then it can add its own [`.tabnine.ignore`](https://docs.rs/ignore/0.4.4/ignore/struct.WalkBuilder.html#method.add_custom_ignore_filename) file as well. So idea is that you put universal ignore rules in `.ignore`, but application specific rules in `.rgignore`, `.fdignore`, `.tabnine.ignore`, etc.

**Comment by zxqfl** [comment]
Added .tabnineignore. @BurntSushi TabNine does use `ignore`, as well as `regex` -- thanks for the great libraries!
