### ISSUE TITLE
Semantic Completion setup with Yarn Package Manager

### ISSUE THREAD

**Issue by bloycey** [zxqfl/TabNine#80]
When trying to set up semantic completion the setup kept failing because it was trying to run `npm install -g yarn flow-bin`. I use Yarn instead and thought that installing through yarn would resolve this problem. It didn't. I ended up having to install npm so that the the semantic completion setup would complete.

Not a huge issue but something to consider as many workplaces prefer to use Yarn rather than NPM nowadays. :smile:

**Comment by athiwatc** [comment]
Hmm, install via `yarn` should work. Did you add the `global yarn` to path?

**Comment by bloycey** [comment]
I'm fairly sure that I added global, yes. However, I'm open that it might have been user error. :joy:

**Comment by zxqfl** [comment]
TabNine's current behavior is to try the semantic completer command first and only run the install command if the semantic completer fails to start. I'm closing this issue as I think this behavior covers this use case unless you can recommend a different command to start the semantic completer.
