### ISSUE TITLE
cursor position after autocomplete in vscode

### ISSUE THREAD

**Issue by happyangry** [zxqfl/TabNine#86]
Hi.

There is a bit problem with cursor position after autocomplete but not all the time.

Before:
![TIM截图20190718111738](https://user-images.githubusercontent.com/21305646/61426818-50d21800-a94e-11e9-92ba-5fc2d8521527.jpg)

After:
![TIM截图20190718111810](https://user-images.githubusercontent.com/21305646/61426820-54659f00-a94e-11e9-9ee5-ccff6fabab2c.jpg)

If the autocomplete is a function with brackets, then the cursor appears in the middle of the brackets after completion. But this situation has appeared in the middle of `Dropout`.

btw why is there no `Tab+2` or `Tab+3` in my autocomplete candidates? I can only use `Tab`  to choose the first candidate.

**Comment by ppnman** [comment]
I have the exactly same problem and question.

**Comment by h1ac0k** [comment]
same problem in php.

**Comment by zxqfl** [comment]
This issue should be fixed by an update to the VS Code plugin, please reopen if it persists.

**Comment by zxqfl** [comment]
Specifically, https://github.com/zxqfl/tabnine-vscode/commit/ebebe27423077940d9cab724fc1a3d839b814ede
