### ISSUE TITLE
Get version 2.0.2 for Deep TabNine

### ISSUE THREAD

**Issue by rpandey4** [zxqfl/TabNine#92]
I am confused how to update to version 2.0.2 for Deep TabNine. I have got the beta sign up mail. But it says to update the TabNine to version 2.0.2. But for every editor, in which I installed TabNine, none of them were 2.0.2. Also, I am not redirected to the webpage when I type TabNine::config. Please help.

**Comment by zxqfl** [comment]
Hi. The binary is supposed to update itself automatically upon startup. What is your platform (OS and 32 vs 64 bit)?

**Comment by Tseka85** [comment]
os 64

пн, 22 июля 2019, 22:24 Jacob Jackson <notifications@github.com>:

**Comment by Tseka85** [comment]
PyCharm

пн, 22 июля 2019, 22:21 Rahul Pandey <notifications@github.com>:

**Comment by miguelpuyol** [comment]
VS code instructions are also obsolete for Mac OS. I do not see anywhere where I can enter the api key

**Comment by athiwatc** [comment]
@zxqfl Do you still need to type `TabNine::become_beta_tester`?

**Comment by rpandey4** [comment]
> Hi. The binary is supposed to update itself automatically upon startup. What is your platform (OS and 32 vs 64 bit)?

macOS Mojave 10.14.5 64 bit

I tried to even restart my system but haven't seen the change in the version in any of my editor.

**Comment by rpandey4** [comment]
TabNine version in the different editor:
1. vim 1.0.9
2. Atom 0.5.6
3. VS Code 1.0.10
4. Sublime Text 1.0.7

**Comment by athiwatc** [comment]
@rpandey4 You are looking at the TabNine extension version. You should be looking at `TabNine::version` that should tell you the TabNine binary version which should be `2.0.2` currently.

**Comment by zxqfl** [comment]
@athiwatc No, it's not necessary anymore.

@rpandey4 Does the command `curl https://update.tabnine.com/2.0.2/x86_64-apple-darwin/TabNine > /dev/null` work for you?

**Comment by lsqshr** [comment]
I am seeing the same thing on Ubuntu. For sublime text, the installed value from TabNine::version is 1.0.7 So TabNine::config does not trigger anything

**Comment by zxqfl** [comment]
It sounds like the automatic update didn't succeed. Can you try restarting Sublime and see if that fixes the issue?

**Comment by lsqshr** [comment]
Yes. I restarted sublime text and the system. No luck. Is there a way to
manually update it o Linux? I'm quite curious about the DEEP version.

**Comment by rpandey4** [comment]
> curl https://update.tabnine.com/2.0.2/x86_64-apple-darwin/TabNine > /dev/null

Yes, the curl command works. That means I guess, it's not because of any server error.

**Comment by zxqfl** [comment]
The version packaged with VS Code is now 2.1.11 so getting 2.0.2 shouldn't be a problem anymore — in general this issue is probably related to the known lack of proxy support.
