### ISSUE TITLE
any plans for supporting jupyter notebook

### ISSUE THREAD

**Issue by gerard0315** [zxqfl/TabNine#95]

**Comment by wenmin-wu** [comment]
I write a Jupyter notebook code autocompletion plugin based on the code of tabnine vscode plugin.  However I can't release it due to lack the permission of the owner.

**Comment by wenmin-wu** [comment]
@gerard0315 https://github.com/wenmin-wu/jupyter-tabnine welcome to contribute.

**Comment by zxqfl** [comment]
https://github.com/wenmin-wu/jupyter-tabnine looks great, thank you for creating it! It will be added to the website soon.

**Comment by anmolp1** [comment]
Does it support JupyterLab?

**Comment by Nick-Dat-Le** [comment]
> Does it support JupyterLab?

This feature would be great. I think tabnine is better than the built in lynter in jupyterlab.

**Comment by dancebean** [comment]
> Does it support JupyterLab?

As far as I can tell, the latest version it's not working with JupyterLab yet (as of today)
