### ISSUE TITLE
Use TypeScript type references for Autocompletions

### ISSUE THREAD

**Issue by janbaer** [zxqfl/TabNine#96]
Is there any way, that TabNine could use the type definitions from TypeScript for using it in the suggested list of functions and properties for the Autocompletion?

Actually types will be referenced in TypeScript but also JavaScript files like this,

```
/// <reference types="Cypress" />
```

VisualStudioCode can read such types reference and provide a better Codecompletion.

I actually use TabNine within VIM and it would be great, when TabNine would support this feature.

**Comment by Shougo** [comment]
You should upload the screeshot for difference.

**Comment by janbaer** [comment]
![vscode-types-autocompletion](https://user-images.githubusercontent.com/528331/61804200-cbf66b00-ae33-11e9-95c7-a34dc5f8ca76.png)

This is how it looks in VSCode. In VIM only the following functions were suggested

![vim-types-autocompletion](https://user-images.githubusercontent.com/528331/61804322-05c77180-ae34-11e9-93bf-5b2dce4602b6.png)

**Comment by Shougo** [comment]
In Vim, semantic completion doesn't work.

**Comment by Shougo** [comment]
Hm.  It can be support in Tabnine?
It should be supported in LSP level.

**Comment by janbaer** [comment]
I also thought that semantic completion should be possible because of the LSP. But I'm not sure about how to read the link to the reference file and if it could be imported.

**Comment by Shougo** [comment]
> VisualStudioCode can read such types reference and provide a better Codecompletion.

It does not mean LSP supports the feature.

**Comment by zxqfl** [comment]
This is out of scope for TabNine, but if you can find a language server that supports this feature I can include it in TabNine's default configuration.

**Comment by janbaer** [comment]
I was trying to find out how it's working in VSCode. But it seems that it's part of the communication between client and server when using the LSP.

https://microsoft.github.io/language-server-protocol/specification#textDocument_typeDefinition

So when Typescript or also JavaScript files will be loading and the client find some reference definitions it could ask the server about a link where the typedefinition can be found. To be honest I don't have enough knowledge about how it's working in details and what is the role of TabNine here.
