### ISSUE TITLE
how can I try it?

### ISSUE THREAD

**Issue by honbolau** [zxqfl/TabNine#97]
VSCode！
Can I enter TabNine::active to display no, how can I try it?
![image](https://user-images.githubusercontent.com/7023387/61813613-b8212800-ae78-11e9-9ff2-e49652126edb.png)

**Comment by yqrashawn** [comment]
You can still try it without [premium license](https://tabnine.com/buy).

**Comment by zxqfl** [comment]
yqrashawn is correct
